github_url: https://github.com/r00tb3
#google_url: https://plus.google.com/+DhavalKapildk
twitter_url: https://twitter.com/r00tb3
linkedin_url: https://in.linkedin.com/in/amitvitekar
keybase_url: https://keybase.io/r00tb3
about_url: /about/
archive_url: /archive/
projects_url: /projects/
contact_url: /contact/
disclaimer_url: /disclaimer/
#resume_url: /resume.pdf
rss_url: /atom.xml
sitemap_url: /sitemap.xml